name: Publish

on:
  workflow_dispatch:

jobs:
  publish-addon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Increase version and update file
      id: version_update
      run: |
        #!/usr/bin/env python3
        import re
        with open('__init__.py', 'r') as file:
            content = file.read()
            version = re.search(r'\"version\": \((\d+), (\d+), (\d+)\)', content).groups()
            new_version = (int(version[0]), int(version[1]), int(version[2]) + 1)
            new_version_str = f'{new_version[0]}.{new_version[1]}.{new_version[2]}'
            content = re.sub(r'\$\{version\}', new_version_str, content)
            content = re.sub(r'\"version\": \(\d+, \d+, \d+\)', f'\"version\": {new_version}', content)
        with open('__init__.py', 'w') as file:
            file.write(content)
        print(f"::set-output name=new_version::{new_version_str}")

    - name: Zip source files
      run: |
        zip -r artifact.zip src/
        echo "Source files zipped into artifact.zip."

    - name: Read Changelog
      id: changelog
      run: |
        changelog=$(cat src/latest_changelog.md)
        echo "::set-output name=changelog::$changelog"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version_update.outputs.new_version }}
        release_name: Release v${{ steps.version_update.outputs.new_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifact.zip
        asset_name: rasqui_celshading-v${{ steps.version_update.outputs.new_version }}.zip
        asset_content_type: application/zip
