name: Publish

on:
  workflow_dispatch:

jobs:
  publish-addon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Increase version and update file
      id: version_increase
      run: python3 .github/increase_version.py

    - name: Commit and push if changed
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add __init__.py
        git commit -m "Update version number"
        git push origin main

    - name: Update file with new version number
      id: version_update
      run: python3 .github/update_version.py

    - name: Zip source files
      run: |
        mkdir rasqui-celshading
        cp -r src/* rasqui-celshading/
        zip -r artifact.zip rasqui-celshading/
        rm -rf rasqui-celshading
        echo "Source files zipped into artifact.zip with root folder renamed."

    - name: Read Changelog
      id: changelog
      run: |
        changelog=$(cat src/latest_changelog.md)
        echo "::set-output name=changelog::$changelog"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_CELSHADING_TOKEN }}
      with:
        tag_name: v${{ steps.version_update.outputs.new_version }}
        release_name: Release v${{ steps.version_update.outputs.new_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_CELSHADING_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifact.zip
        asset_name: rasqui_celshading-v${{ steps.version_update.outputs.new_version }}.zip
        asset_content_type: application/zip
